// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9j4KbUp-CBGmWYo7SxFpocCaxjSDQnE',
    appId: '1:985005330847:web:6751bc2cbfe2561a616daa',
    messagingSenderId: '985005330847',
    projectId: 'riverpod-chat-5253c',
    authDomain: 'riverpod-chat-5253c.firebaseapp.com',
    storageBucket: 'riverpod-chat-5253c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNge_7Ur4IeicdMmOqtM_iXAvtWZUHWk',
    appId: '1:985005330847:android:6e55ada8a96adfd7616daa',
    messagingSenderId: '985005330847',
    projectId: 'riverpod-chat-5253c',
    storageBucket: 'riverpod-chat-5253c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5GMCBYsjYe7MmgdEaBIn1r5w3kUrDTU',
    appId: '1:985005330847:ios:113f0281fd28c689616daa',
    messagingSenderId: '985005330847',
    projectId: 'riverpod-chat-5253c',
    storageBucket: 'riverpod-chat-5253c.appspot.com',
    iosBundleId: 'com.example.flutterBlog2',
  );
}
